name: Deploy RPA Docker

on:
  push:
    branches:
      - main  # Cambia a la rama que usas para producción (main, master, etc.)
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "Byronde1995." | docker login -u "alexhm95" --password-stdin

      - name: Build and tag Docker image
        run: docker build -f Dockerfile -t alexhm95/rpa_contratos:latest .

      - name: Push Docker image
        run: docker push alexhm95/rpa_contratos:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 190.96.96.20
          username: proyectos
          password: proyectos25
          script: |
            docker pull alexhm95/rpa_contratos:latest
            docker stop f4064af2d876  || true
            docker rm f4064af2d876  || true
            docker run -d --name f4064af2d876  alexhm95/rpa_contratos:latest