name: Deploy RPA Docker

on:
  push:
    branches:
      - master  # Cambia a la rama que usas para producción (main, master, etc.)      
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: docker build -f Dockerfile -t alexhm95/rpa_odoo:latest .

      - name: Push Docker image
        run: docker push alexhm95/rpa_odoo:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST_SERVER }}"
          username: "${{ secrets.USER_SERVER }}"
          password: "${{ secrets.PASS_SERVER }}"
          port : "${{ secrets.PORT_SERVER }}"
          script: |
            docker pull alexhm95/rpa_odoo:latest

            echo "Verificando si existe rpa_odoo_cache_holder..."
            EXISTS=$(docker ps -a --filter "name=rpa_odoo_cache_holder" --format "{{.Names}}")
            
            if [ "$EXISTS" == "rpa_odoo_cache_holder" ]; then
              echo "Contenedor existente, eliminando..."
              docker rm rpa_odoo_cache_holder
            fi
            
            echo "Creando contenedor rpa_odoo_cache_holder..."
            docker create --name rpa_odoo_cache_holder alexhm95/rpa_odoo:latest

