name: Deploy RPA Docker

on:
  push:
    branches:
      - main  # O la rama que uses para producción
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: docker build -t usuario/docker-rpa:latest .

      - name: Push Docker image
        run: docker push usuario/docker-rpa:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull usuario/docker-rpa:latest
            docker stop rpa_container || true
            docker rm rpa_container || true
            docker run -d --name rpa_container usuario/docker-rpa:latest
