name: Deploy RPA Docker

on:
  push:
    branches:
      - master  # Cambia a la rama que usas para producción (main, master, etc.)      
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: docker build -f Dockerfile -t alexhm95/rpa_odoo:latest .

      - name: Push Docker image
        run: docker push alexhm95/rpa_odoo:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST_SERVER }}"
          username: "${{ secrets.USER_SERVER }}"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port : "${{ secrets.PORT_SERVER }}"
          script: |
            echo "Starting deployment script..."
            cd /home/administrador/Robots/RPA_Contratos
            git config --global --add safe.directory /home/administrador/Robots/RPA_Contratos
            echo "Updating repository..."
            git reset --hard
            git fetch
            git pull origin master
            echo "Repository updated."

            echo "Permissions updated."
            chmod +x deploy.sh
            ./deploy.sh
            echo "Deployment script finished."
        

